export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_PASSWORD_CHANGE = "USER_PASSWORD_CHANGE";

export const AUTHENTICATOR_REQUEST = "AUTHENTICATOR_REQUEST";
export const AUTHENTICATOR_ENABLE_REQUEST = "AUTHENTICATOR_ENABLE_REQUEST";
export const AUTHENTICATOR_ENABLE_SUCCESS = "AUTHENTICATOR_ENABLE_SUCCESS";
export const AUTHENTICATOR_ENABLE_ERROR = "AUTHENTICATOR_ENABLE_ERROR";
export const AUTHENTICATOR_DISABLE_REQUEST = "AUTHENTICATOR_DISABLE_REQUEST";
export const AUTHENTICATOR_DISABLE_SUCCESS = "AUTHENTICATOR_DISABLE_SUCCESS";
export const AUTHENTICATOR_DISABLE_ERROR = "AUTHENTICATOR_DISABLE_ERROR";
export const AUTHENTICATOR_RESET_REQUEST = "AUTHENTICATOR_RESET_REQUEST";
export const AUTHENTICATOR_RESET_SUCCESS = "AUTHENTICATOR_RESET_SUCCESS";
export const AUTHENTICATOR_RESET_ERROR = "AUTHENTICATOR_RESET_ERROR";
export const AUTHENTICATOR_CODES_REQUEST = "AUTHENTICATOR_CODES_REQUEST";
