export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_REFRESH_TOKEN = "AUTH_REFRESH_TOKEN";
export const AUTH_VERIFICATION_REQUEST = "AUTH_VERIFICATION_REQUEST";
export const AUTH_RECOVERY_REQUEST = "AUTH_RECOVERY_REQUEST";
export const AUTH_TWOFACTOR = "AUTH_TWOFACTOR";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
